#!/usr/bin/env bash
set -o errexit

main() {
  if [[ $DEBUG ]]; then
    set -o xtrace
  fi

  unset TRAVIS_WORKER_DOCKER_CREDS
  unset TRAVIS_WORKER_DOCKER_DEST
  unset TRAVIS_WORKER_DOCKER_LOGIN_PASSWORD
  unset TRAVIS_WORKER_DOCKER_LOGIN_USERNAME
  unset DOCKER_CREDS
  unset DOCKER_DEST
  unset DOCKER_LOGIN_PASSWORD
  unset DOCKER_LOGIN_USERNAME

  local sudo_exe=(sudo)

  if ! sudo true &>/dev/null; then
    sudo_exe=(echo not sudo)
  fi

  cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")"

  "${sudo_exe[@]}" mkdir -p /var/log/upstart

  echo '---> Installing travis-worker edge with tracing'
  "${sudo_exe[@]}" ./bin/travis-worker-install --trace --skip-docker-populate --edge

  /usr/local/bin/travis-worker --version

  local docker_version
  docker_version="$(docker version --format '{{.Server.Version}}')"
  if [[ ! "${docker_version}" =~ 17\.[0-9][0-9]\.[0-9] ]]; then
    echo "     ERROR: unexpected docker server version" >&2
    echo "     ERROR:   expected: 17.[0-9][0-9].[0-9]" >&2
    echo "     ERROR:     actual: ${docker_version}" >&2
    docker version
    exit 1
  fi

  if ! docker run hello-world; then
    "${sudo_exe[@]}" tail -n 1000 /var/log/upstart/docker.log
  fi

  echo '---> Uninstalling travis-worker and docker-engine'
  "${sudo_exe[@]}" apt-get purge -y travis-worker docker-engine
  "${sudo_exe[@]}" mv -v /var/lib/docker /var/lib/docker.bak

  echo '---> Wiping logs'
  "${sudo_exe[@]}" touch /var/log/upstart/travis-worker.log
  "${sudo_exe[@]}" touch /var/log/upstart/docker.log
  "${sudo_exe[@]}" dd if=/dev/null of=/var/log/upstart/travis-worker.log
  "${sudo_exe[@]}" dd if=/dev/null of=/var/log/upstart/docker.log

  echo '---> Wiping and updating apt sources'
  find /etc/apt/sources.list.d -name '*travisci_worker*' -print0 |
    xargs -0 "${sudo_exe[@]}" rm -vf
  "${sudo_exe[@]}" apt-get update

  echo '---> Installing travis-worker stable'
  "${sudo_exe[@]}" ./bin/travis-worker-install --skip-docker-populate --stable

  local docker_version
  docker_version="$(docker version --format '{{.Server.Version}}')"
  if [[ ! "${docker_version}" =~ 17\.[0-9][0-9]\.[0-9] ]]; then
    echo "     ERROR: unexpected docker server version" >&2
    echo "     ERROR:   expected: 17.[0-9][0-9].[0-9]" >&2
    echo "     ERROR:     actual: ${docker_version}" >&2
    docker version
    exit 1
  fi

  if ! docker run hello-world; then
    "${sudo_exe[@]}" tail -n 1000 /var/log/upstart/docker.log
  fi
  "${sudo_exe[@]}" apt-get purge -y travis-worker ||
    echo "Suppressing exit $? from purge of travis-worker stable"
}

main "$@"
