#!/usr/bin/env bash
set -o errexit

main() {
  if [[ $DEBUG ]]; then
    set -o xtrace
  fi

  : "${OS:=$(go env GOHOSTOS)}"
  : "${ARCH:=$(go env GOHOSTARCH)}"

  cd "$(dirname "$(dirname "${BASH_SOURCE[0]}")")"

  git diff --exit-code
  git diff --cached --exit-code
  "./build/${OS}/${ARCH}/travis-worker" --version
  "./build/${OS}/${ARCH}/travis-worker" -v | grep -v '\?'
  "./build/${OS}/${ARCH}/travis-worker" --help
  "./build/${OS}/${ARCH}/travis-worker" -h
  diff -q \
    <("./build/${OS}/${ARCH}/travis-worker" --help) \
    <("./build/${OS}/${ARCH}/travis-worker" -h)
  N="${RANDOM}"
  TRAVIS_WORKER_FOO_N="${N}" "./build/${OS}/${ARCH}/travis-worker" \
    --echo-config \
    --provider-name=foo | grep "^export TRAVIS_WORKER_FOO_N=\"${N}\"\$"
  "./build/${OS}/${ARCH}/travis-worker" --echo-config
  "./build/${OS}/${ARCH}/travis-worker" --list-backend-providers
}

main "$@"
