#!/usr/bin/env bash

main() {
  if [[ $TRAVIS_PULL_REQUEST != false ]] ; then
    echo 'This is a pull request. No deployment will be done.'
    exit 0
  fi

  if [[ $TRAVIS_BRANCH != master ]] ; then
    echo 'Testing on a branch other than master. No deployment will be done.'
    exit 0
  fi

  local gopath_top="${GOPATH%%:*}"

  echo 'Installing Atlas Upload CLI'
  go get github.com/hashicorp/atlas-upload-cli
  pushd ${gopath_top}/src/github.com/hashicorp/atlas-upload-cli
  make
  popd

  echo 'Building Worker'
  make build

  echo 'Uploading Worker'
  ${gopath_top}/src/github.com/hashicorp/atlas-upload-cli/bin/atlas-upload \
    travis-ci/worker ${gopath_top}/bin/travis-worker
}

main "$@"
