#!/usr/bin/env bash

set -e
shopt -s nullglob

cd $(dirname $(dirname ${BASH_SOURCE[0]}))

rm -rvf \
  ./build \
  ${GOPATH%%:*}/bin/travis-worker \
  coverage.html \
  *coverage.coverprofile \
  ./tmp/deb \
  ./tmp/output \
  .docker.env

find ${GOPATH%%:*}/pkg -wholename '*travis-ci/worker*.a' | \
  grep -v vendor/ | \
  xargs rm -vf
