#!/bin/bash

set -e

GO=${GO:-go}
PACKAGE=${PACKAGE:-github.com/travis-ci/worker}
PACKAGE_CHECKOUT=$PWD
SUBPACKAGES=$(find . -type d | grep -v 'src|vendor|text|bin')

cd $PACKAGE_CHECKOUT
rm -vf "./bin/travis-worker"
rm -vf coverage.html *coverage.coverprofile
${GO} clean ${PACKAGE} || true
