#!/usr/bin/env bash

set -o errexit

main() {
  [[ ${DOCKER_DEST} ]] || {
    __log error="missing \$DOCKER_DEST"
    exit 1
  }

  set -o xtrace
  docker run --rm "${DOCKER_DEST}" --version &>/dev/null
  docker run --rm "${DOCKER_DEST}" travis-worker --version &>/dev/null
  docker run --rm "${DOCKER_DEST}" --help &>/dev/null
  docker run --rm "${DOCKER_DEST}" travis-worker --help &>/dev/null
}

__log() {
  echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$@"
}

main "$@"
