#!/bin/bash

set -e

gofmt_check () {

  f="$1"
  gofmt ${f} | if ! diff -u ${f} - ; then
  echo fmtpolice:${f} ✗
    exit 1
  else
    echo fmtpolice:${f} ✓
  fi

}
for f in $(git ls-files '*.go' | grep -v vendor/) ; do
  gofmt_check ${f}
done

echo
echo ★★★★★ ALL HAPPY ★★★★★
