#!/bin/bash

set -e

if [[ $# -lt 1 ]] ; then
  echo "Usage: $(basename $0) [coverprofile, coverprofile, ...]"
  exit 1
fi

GO=${GO:-deppy go}
OUT_TMP=$(mktemp worker.XXXXX)
PACKAGE=${PACKAGE:-github.com/travis-ci/worker}

trap "rm -f $OUT_TMP" EXIT TERM QUIT

${GO} test \
  -covermode=count \
  -coverprofile=${OUT_TMP} \
  ${GOBUILD_LDFLAGS} \
  ${PACKAGE} 1>&2

echo 'mode: count'
grep -h -v 'mode: count' "${OUT_TMP}" || true
grep -h -v 'mode: count' $*
