#!/usr/bin/env bash

set -e

pushd $(dirname $(dirname ${BASH_SOURCE[0]}))

: ${CYCLOMAX:=20}
: ${DEADLINE:=1m}
: ${PACKAGE:=github.com/travis-ci/worker}

DISABLED_LINTER_FLAGS=''

# FIXME: figure out what's going on with gotype's GOPATH
DISABLED_LINTER_FLAGS="$DISABLED_LINTER_FLAGS --disable=gotype"

# FIXME: do we care about shadowing `ctx` everywhere?
DISABLED_LINTER_FLAGS="$DISABLED_LINTER_FLAGS --disable=go-nyet"

# FIXME: this probably warrants fixing
DISABLED_LINTER_FLAGS="$DISABLED_LINTER_FLAGS --disable=errcheck"

# FIXME: this probably warrants fixing
DISABLED_LINTER_FLAGS="$DISABLED_LINTER_FLAGS --disable=dupl"

GOMETALINTER_ARGS="${DISABLED_LINTER_FLAGS} --deadline=${DEADLINE}"
GOMETALINTER_ARGS="${GOMETALINTER_ARGS} --cyclo-over=${CYCLOMAX} --vendor"
GOMETALINTER_ARGS="${GOMETALINTER_ARGS} --tests"

if [[ $DEBUG ]] ; then
  GOMETALINTER_ARGS="$GOMETALINTER_ARGS --debug"
else
  GOMETALINTER_ARGS="$GOMETALINTER_ARGS --errors"
fi

set -o xtrace
exec gometalinter $GOMETALINTER_ARGS ./...
