#!/usr/bin/env bash

set -e

cd $(dirname $(dirname ${BASH_SOURCE[0]}))

for pkg in $(find src/github.com/travis-ci/worker -type d | sed 's@src@@;s@^/@@'); do
  if [[ "x$(bash -c "shopt -s nullglob; echo src/${pkg}/*.go")" = "x" ]] ; then
    continue
  fi
  echo "${pkg}"
done
