#!/usr/bin/env bash

set -e

cd $(dirname $(dirname ${BASH_SOURCE[0]}))

for pkg in $(find . -maxdepth 1 -type d | grep -v '^\.$' | sed 's@./@@'); do
  if [[ "x$(bash -c "shopt -s nullglob; echo ${pkg}/*.go")" = "x" ]] ; then
    continue
  fi
  echo "github.com/travis-ci/worker/${pkg}"
done
