#!/usr/bin/env bash

main() {
  : ${CHECKOUT_ROOT:=${TRAVIS_BUILD_DIR:-/code}}
  source ${CHECKOUT_ROOT}/utils/package-functions.bash
  source ${CHECKOUT_ROOT}/utils/package-config.bash

  __define_platform "$1"

  : ${PACKAGE_TYPE:=${2}}

  export CHECKOUT_ROOT PLATFORM PLATFORM_FAMILY PLATFORM_RELEASE PACKAGE_TYPE

  if ! ruby -v &>/dev/null ; then
    __announce 'Installing ruby & fpm'
    __install_fpm_prereqs_${PLATFORM_FAMILY} 2>&1 | __indent
    __install_fpm 2>&1 | __indent
  fi

  __announce 'Setting up directories to build packages'
  __setup_working_dirs 2>&1 | __indent
  __announce 'Copying travis-worker binary into build directory'
  __copy_binary 2>&1 | __indent
  __announce 'Setting up service scripts'
  __copy_service_scripts 2>&1 | __indent
  __announce "Building package for $PLATFORM with fpm"
  __run_fpm 2>&1 | __indent
}

__install_fpm_prereqs_centos() {
  yum groupinstall 'Development Tools' -y
  yum install ruby ruby-devel -y
}

__install_fpm_prereqs_ubuntu_precise() {
  apt-get install python-software-properties -y
}

__install_fpm_prereqs_ubuntu_trusty() {
  apt-get install software-properties-common -y
}

__install_fpm_prereqs_ubuntu() {
  apt-get update
  __install_fpm_prereqs_ubuntu_${PLATFORM_RELEASE}
  apt-add-repository ppa:brightbox/ruby-ng -y
  apt-get update
  apt-get install build-essential ruby2.1 libruby2.1 ruby2.1-dev -y
}

__install_fpm() {
  gem install fpm --no-ri --no-rdoc
}

__setup_working_dirs() {
  mkdir -p tmp/$PACKAGE_TYPE/usr/local/bin
  mkdir -p tmp/output/$PACKAGE_TYPE/$PLATFORM_FAMILY/$PLATFORM_RELEASE
}

__copy_binary() {
  cp -v \
    $CHECKOUT_ROOT/build/linux/amd64/travis-worker \
    tmp/$PACKAGE_TYPE/usr/local/bin
}

__copy_service_scripts() {
  rsync -av \
    $CHECKOUT_ROOT/utils/package-overlay.d/common/ \
    tmp/$PACKAGE_TYPE/
  rsync -av \
    $CHECKOUT_ROOT/utils/package-overlay.d/$PACKAGE_TYPE/ \
    tmp/$PACKAGE_TYPE/
}

__run_fpm() {
  fpm -f -s dir \
    --log info \
    -t "$PACKAGE_TYPE" \
    -p "tmp/output/$PACKAGE_TYPE/$PLATFORM_FAMILY/$PLATFORM_RELEASE" \
    --after-install $CHECKOUT_ROOT/utils/package-templates.d/post_install.sh \
    --before-remove $CHECKOUT_ROOT/utils/package-templates.d/pre_remove.sh \
    -n travis-worker \
    --url 'https://github.com/travis-ci/worker' \
    --description 'Travis Worker' \
    -v "$VERSION" \
    -C "tmp/$PACKAGE_TYPE" \
    .

  chmod -R 777 "$CHECKOUT_ROOT/tmp"
}

main "$@"
