#!/usr/bin/env bash

main() {
  : ${CHECKOUT_ROOT:=${TRAVIS_BUILD_DIR:-/code}}
  source ${CHECKOUT_ROOT}/utils/pkg-functions.bash
  source ${CHECKOUT_ROOT}/utils/pkg-config.bash

  __define_shell_flags
  __define_platform "$1"
  __announce 'Installing package'
  __package_install_${PLATFORM_FAMILY} 2>&1 | __indent
  __announce 'Verifying package installation'
  __package_verify_common 2>&1 | __indent
  __package_verify_${PLATFORM_FAMILY} 2>&1 | __indent
  __announce 'Package verified'
  __package_verify_report 2>&1 | __indent
}

__package_install_centos() {
  rpm -i tmp/output/rpm/centos/${PLATFORM_RELEASE}/*.rpm
}

__package_install_ubuntu() {
  dpkg -i tmp/output/deb/ubuntu/${PLATFORM_RELEASE}/*.deb
}

__package_verify_ubuntu() {
  if apt-cache show travis-worker &>/dev/null ; then
    __log 'Package installed successfully'
    dpkg -c /code/tmp/output/deb/ubuntu/${PLATFORM_RELEASE}/*.deb
    apt-cache show travis-worker
  else
    __error 'Package did not install'
    exit 1
  fi
  __log 'Testing service installation'
  initctl list 2>&1 | grep -q travis-worker
}

__package_verify_centos() {
  if yum info travis-worker &>/dev/null ; then
    __log 'Package installed successfully'
    rpm -qlp /code/tmp/output/rpm/centos/${PLATFORM_RELEASE}/*.rpm
    yum info travis-worker
  else
    __error 'Package did not install'
    exit 1
  fi
  __log 'Testing service installation'
  systemctl enable travis-worker &>/dev/null
}

__package_verify_common() {
  __log 'Testing travis user'
  if getent passwd travis &>/dev/null ; then
    __log 'User created successfully'
    return
  fi

  __error 'User not found'
}
  
__package_verify_report() {
  touch "${CHECKOUT_ROOT}/${PLATFORM}-${PLATFORM_PACKAGE_TYPE}-success"
}

main "$@"
