#!/usr/bin/env bash

main() {
  : ${CHECKOUT_ROOT:=${TRAVIS_BUILD_DIR:-/code}}
  source ${CHECKOUT_ROOT}/utils/pkg-functions.bash
  source ${CHECKOUT_ROOT}/utils/pkg-config.bash

  __define_shell_flags
  __define_platform "$1"
  __package_install 2>&1 | __indent
  __package_verify 2>&1 | __indent
}

__package_install () {
  __announce 'Installing package'

  local lsb_codename=$(lsb_release -sc)

  if [[ $lsb_codename =~ precise|trusty ]] ; then
    dpkg -i tmp/output/deb/ubuntu/${lsb_codename}/*.deb
  elif [[ -f /etc/redhat-release ]] ; then
    rpm -i tmp/output/rpm/centos/7/*.rpm
  fi
}

__package_verify () {
  __announce 'Verifying package installation'

  __log 'Testing travis user'
  if getent passwd travis &>/dev/null ; then
    __log 'User created successfully'
  else
    __error 'User not found'
  fi

  if [[ $PLATFORM_FAMILY = ubuntu ]] ; then
    if apt-cache show travis-worker &>/dev/null ; then
      __log 'Package installed successfully'
      dpkg -c /code/tmp/output/deb/ubuntu/${PLATFORM_RELEASE}/*.deb
      apt-cache show travis-worker
    else
      __error 'Package did not install'
      exit 1
    fi
    __log 'Testing service installation'
    initctl list 2>&1 | grep -q travis-worker
  fi

  if [[ $PLATFORM_FAMILY = centos ]] ; then
    if yum info travis-worker &>/dev/null ; then
      __log 'Package installed successfully'
      rpm -qlp /code/tmp/output/rpm/centos/${PLATFORM_RELEASE}/*.rpm
      yum info travis-worker
    else
      __error 'Package did not install'
      exit 1
    fi
    __log 'Testing service installation'
    systemctl enable travis-worker &>/dev/null
  fi

  touch "${CHECKOUT_ROOT}/${PLATFORM}-${PLATFORM_PACKAGE_TYPE}-success"
  __log 'Package verified'
}

main "$@"
