#!/usr/bin/env bash

main() {
  set -o errexit
  if [[ $DEBUG ]] ; then
    set -o xtrace
  fi

  local sudo_exe='sudo'

  if ! sudo true &>/dev/null ; then
    sudo_exe='echo not sudo'
  fi

  cd "$(dirname $(dirname ${BASH_SOURCE[0]}))"

  ${sudo_exe} mkdir -p /var/log/upstart

  echo '---> Installing travis-worker edge with tracing'
  ${sudo_exe} ./bin/travis-worker-install --trace --skip-docker-populate --edge
  /usr/local/bin/travis-worker --version
  docker version | grep 1.9.0
  if ! docker run hello-world ; then
    ${sudo_exe} tail -n 1000 /var/log/upstart/docker.log
  fi

  echo '---> Uninstalling travis-worker and docker-engine'
  ${sudo_exe} apt-get purge -y travis-worker docker-engine

  echo '---> Wiping logs'
  ${sudo_exe} touch /var/log/upstart/travis-worker.log
  ${sudo_exe} touch /var/log/upstart/docker.log
  ${sudo_exe} dd if=/dev/null of=/var/log/upstart/travis-worker.log
  ${sudo_exe} dd if=/dev/null of=/var/log/upstart/docker.log

  echo '---> Wiping and updating apt sources'
  find /etc/apt/sources.list.d -name '*travisci_worker*' | xargs ${sudo_exe} rm -vf
  ${sudo_exe} apt-get update

  echo '---> Installing travis-worker stable'
  ${sudo_exe} ./bin/travis-worker-install --skip-docker-populate --stable
  /usr/local/bin/travis-worker --version
  docker version | grep 1.6.2
  if ! docker run hello-world ; then
    ${sudo_exe} tail -n 1000 /var/log/upstart/docker.log
  fi
  ${sudo_exe} apt-get purge -y travis-worker || \
    echo "Suppressing exit $? from purge of travis-worker stable"
}

main "$@"
