#!/usr/bin/env bash

set -o errexit

main() {
  if [[ -f "${DOCKER_ENV_FILE}" ]]; then
    # shellcheck source=/dev/null
    source "${DOCKER_ENV_FILE}"
  fi

  [[ ${DOCKER_DEST} ]] || {
    __log error="missing \$DOCKER_DEST"
    exit 1
  }

  unset DOCKER_LOGIN_PASSWORD
  unset DOCKER_LOGIN_USERNAME

  set -o xtrace
  docker run --rm "${DOCKER_DEST}" --version &>/dev/null
  docker run --rm "${DOCKER_DEST}" travis-worker --version &>/dev/null
  docker run --rm "${DOCKER_DEST}" --help &>/dev/null
  docker run --rm "${DOCKER_DEST}" travis-worker --help &>/dev/null
  docker run --rm "${DOCKER_DEST}" curl --version &>/dev/null
  docker run --rm "${DOCKER_DEST}" curl https://www.google.com &>/dev/null
}

__log() {
  echo "time=$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$@"
}

main "$@"
