#!/usr/bin/env bash

main() {
  set -o errexit
  if [[ $DEBUG ]] ; then
    set -o xtrace
  fi

  unset TRAVIS_WORKER_DOCKER_CREDS
  unset TRAVIS_WORKER_DOCKER_DEST
  unset TRAVIS_WORKER_DOCKER_LOGIN_PASSWORD
  unset TRAVIS_WORKER_DOCKER_LOGIN_USERNAME
  unset DOCKER_CREDS
  unset DOCKER_DEST
  unset DOCKER_LOGIN_PASSWORD
  unset DOCKER_LOGIN_USERNAME

  : ${OS:=$(go env GOHOSTOS)}
  : ${ARCH:=$(go env GOHOSTARCH)}

  cd "$(dirname $(dirname ${BASH_SOURCE[0]}))"

  git diff --exit-code
  git diff --cached --exit-code
  ./build/${OS}/${ARCH}/travis-worker --version
  ./build/${OS}/${ARCH}/travis-worker -v | grep -v '\?'
  ./build/${OS}/${ARCH}/travis-worker --help
  ./build/${OS}/${ARCH}/travis-worker -h
  diff -q \
    <(./build/${OS}/${ARCH}/travis-worker --help) \
    <(./build/${OS}/${ARCH}/travis-worker -h)
  N=$RANDOM
  TRAVIS_WORKER_FOO_N=$N ./build/${OS}/${ARCH}/travis-worker \
    --echo-config \
    --provider-name=foo | grep "^export TRAVIS_WORKER_FOO_N=\"$N\"\$"
  ./build/${OS}/${ARCH}/travis-worker --echo-config
  ./build/${OS}/${ARCH}/travis-worker --list-backend-providers
  docker run --rm -i -t \
    -v ${PWD}:/app \
    'alpine:3.4' \
    /app/build/linux/amd64/travis-worker --version
}

main "$@"
