#!/usr/bin/env bash

main() {
  set -o errexit
  if [[ $DEBUG ]] ; then
    set -o xtrace
  fi

  : ${OS:=$(go env GOHOSTOS)}
  : ${ARCH:=$(go env GOHOSTARCH)}

  cd "$(dirname $(dirname ${BASH_SOURCE[0]}))"

  local worker="./build/${OS}/${ARCH}/travis-worker"

  git diff --exit-code
  git diff --cached --exit-code
  $worker --version
  $worker -v | grep -v '\?'
  $worker --help
  $worker -h
  diff -q <($worker --help) <($worker -h)
  $worker echo-config | grep '^export TRAVIS_WORKER'
  $worker echo-config
  $worker list-backend-providers | grep '^docker'
  $worker list-backend-providers
}

main "$@"
